/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.fabric;

import io.fabric.sdk.android.Fabric;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;

import com.crashlytics.android.Crashlytics;
import com.crashlytics.android.answers.Answers;

@Kroll.module(name = "Fabric", id = "ti.fabric")
public class FabricModule extends KrollModule {

	// Standard Debugging variables
	private static final String LCAT = "FabricModule";
	
	public static boolean debuggable = true;

	public FabricModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Log.d(LCAT, "inside onAppCreate");
	}

	@Kroll.method
	public boolean init() {
		try{
			final Fabric fabric = new Fabric.Builder(TiApplication.getInstance())
				.kits(new Crashlytics(), new Answers())
				.debuggable(debuggable)
				.build();
			Fabric.with(fabric);
			return true;
		}catch(Exception exp){
			Log.e(LCAT, exp.getMessage());
			return false;
		}
	}

	@Kroll.method @Kroll.getProperty
	public CrashlyticsModule getCrashlytics()
	{
		final CrashlyticsModule	crashlyticsModule = new CrashlyticsModule();
		return crashlyticsModule;
	}

	@Kroll.method @Kroll.getProperty
	public AnswersModule getAnswers()
	{
		final AnswersModule answersModule = new AnswersModule();
		return answersModule;
	}
}